import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import { NextPage } from "next";
import Image from "next/image";
import deved from "../public/screenshot.png";
//import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web0 from "../public/web0.jpg";
import web03 from "../public/web03.jpg";
import web01 from "../public/web01.jpg";
import web4 from "../public/web4.jpg";
import web5 from "../public/web5.jpg";
import web3 from "../public/web3.jpg";
import web from "../public/web.jpg";
import screenshot from "../public/screenshot.png";
import ContactMe from "@/components/contactMe";

const Home: NextPage = () => {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>G-Wealth </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <Image src={web} width={50} height={50}
            className="rounded-full"
            alt="screenshot"  />
           {/* <h1 className="font-burtons text-xl text-teal-600 font-medium dark:text-teal-400 ">
              G-WEALTH EMPIRE</h1>*/}
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text-to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Projects
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-yellow-600/100 font-medium dark:text-green-700 md:text-6xl">
              G-Wealth
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
             Design || Branding || Web Design || General Printing of all Kind's ||
             Sales of all kind's of Phone Accessaries both in Wholesale and Retail and Sales of
             different qualities of Laptops.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
             your one-stop for captivating graphic designs and high-quality phone accessories !
           
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt="Profile" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services we offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
               In the beginning of my journey as a graphic designer and
               photo edithing, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talented people to create digital design
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              We offer a wide range of services, including brand design, photo Editing and
               phone accessories.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={screenshot} width={50} height={50} alt="Design" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Graphic Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs, business and costumer designs
          
              </p>
              <h4 className="py-4 text-teal-600"> Graphic Design Tools we Use</h4>
              <p className="text-gray-800 py-1">Branding</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Printing</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={screenshot} width={50} height={50} alt="Code" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great designs? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600"> Web Design Tool</h4>
              <p className="text-gray-800 py-1">Website</p>
              <p className="text-gray-800 py-1">Mobile App</p>
              <p className="text-gray-800 py-1">Portfolio</p>
              <p className="text-gray-800 py-1">E-commerce</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={screenshot} width={50} height={50} alt="Consulting" />
              <h3 className="text-lg font-medium pt-8 pb-2 "> Phone Accessories</h3>
              <p className="py-2">
                Are you interested to get higt-quality phone accessories for your phone? Visite G-Wealth one-stop
                captivating phone Accessories shop.
              </p>
              <h4 className="py-4 text-teal-600">Phone Accessories</h4>
              <p className="text-gray-800 py-1">Airpod & Pouch</p>
              <p className="text-gray-800 py-1">Chargers</p>
              <p className="text-gray-800 py-1">Jbl Speaker's</p>
              <p className="text-gray-800 py-1">Screen Guard</p>
              <p className="text-gray-800 py-1">Earphones</p>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-3xl py-1 dark:text-white">Projects</h2>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Here are some of the projects I have worked on:
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web0} width={400} height={300} alt="Project 1" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 1</h3>
                <p className="text-gray-800 py-1">
                  A description of the first web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web03} width={400} height={300} alt="Project 2" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 2</h3>
                <p className="text-gray-800 py-1">
                  A description of the second web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web01} width={400} height={300} alt="Project 3" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 3</h3>
                <p className="text-gray-800 py-1">
                  A description of the third web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web4} width={400} height={300} alt="Project 4" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 4</h3>
                <p className="text-gray-800 py-1">
                  A description of the fourth web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web5} width={400} height={300} alt="Project 5" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 5</h3>
                <p className="text-gray-800 py-1">
                  A description of the fifth web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web3} width={400} height={300} alt="Project 6" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 6</h3>
                <p className="text-gray-800 py-1">
                  A description of the sixth web project.
                </p>
              </div>
            </div>
          </div>
        </section>
       
        <section>
          <h2 className="text-3xl py-1 dark:text-white">Projects</h2>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Here are some of the projects I have worked on:
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web0} width={400} height={300} alt="Project 1" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 1</h3>
                <p className="text-gray-800 py-1">
                  A description of the first web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web03} width={400} height={300} alt="Project 2" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 2</h3>
                <p className="text-gray-800 py-1">
                  A description of the second web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web01} width={400} height={300} alt="Project 3" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 3</h3>
                <p className="text-gray-800 py-1">
                  A description of the third web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web4} width={400} height={300} alt="Project 4" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 4</h3>
                <p className="text-gray-800 py-1">
                  A description of the fourth web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web5} width={400} height={300} alt="Project 5" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 5</h3>
                <p className="text-gray-800 py-1">
                  A description of the fifth web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web3} width={400} height={300} alt="Project 6" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 6</h3>
                <p className="text-gray-800 py-1">
                  A description of the sixth web project.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-3xl py-1 dark:text-white">Projects</h2>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Here are some of the projects I have worked on:
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web0} width={400} height={300} alt="Project 1" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 1</h3>
                <p className="text-gray-800 py-1">
                  A description of the first web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web03} width={400} height={300} alt="Project 2" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 2</h3>
                <p className="text-gray-800 py-1">
                  A description of the second web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web01} width={400} height={300} alt="Project 3" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 3</h3>
                <p className="text-gray-800 py-1">
                  A description of the third web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web4} width={400} height={300} alt="Project 4" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 4</h3>
                <p className="text-gray-800 py-1">
                  A description of the fourth web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web5} width={400} height={300} alt="Project 5" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 5</h3>
                <p className="text-gray-800 py-1">
                  A description of the fifth web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web3} width={400} height={300} alt="Project 6" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 6</h3>
                <p className="text-gray-800 py-1">
                  A description of the sixth web project.
                </p>
              </div>
            </div>
          </div>
        </section>
        
        <section>
          <h2 className="text-3xl py-1 dark:text-white">Projects</h2>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Here are some of the projects I have worked on:
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web0} width={400} height={300} alt="Project 1" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 1</h3>
                <p className="text-gray-800 py-1">
                  A description of the first web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web03} width={400} height={300} alt="Project 2" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 2</h3>
                <p className="text-gray-800 py-1">
                  A description of the second web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web01} width={400} height={300} alt="Project 3" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 3</h3>
                <p className="text-gray-800 py-1">
                  A description of the third web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web4} width={400} height={300} alt="Project 4" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 4</h3>
                <p className="text-gray-800 py-1">
                  A description of the fourth web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web5} width={400} height={300} alt="Project 5" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 5</h3>
                <p className="text-gray-800 py-1">
                  A description of the fifth web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web3} width={400} height={300} alt="Project 6" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 6</h3>
                <p className="text-gray-800 py-1">
                  A description of the sixth web project.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-3xl py-1 dark:text-white">Projects</h2>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Here are some of the projects I have worked on:
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web0} width={400} height={300} alt="Project 1" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 1</h3>
                <p className="text-gray-800 py-1">
                  A description of the first web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web03} width={400} height={300} alt="Project 2" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 2</h3>
                <p className="text-gray-800 py-1">
                  A description of the second web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web01} width={400} height={300} alt="Project 3" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 3</h3>
                <p className="text-gray-800 py-1">
                  A description of the third web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web4} width={400} height={300} alt="Project 4" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 4</h3>
                <p className="text-gray-800 py-1">
                  A description of the fourth web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web5} width={400} height={300} alt="Project 5" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 5</h3>
                <p className="text-gray-800 py-1">
                  A description of the fifth web project.
                </p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
              <Image src={web3} width={400} height={300} alt="Project 6" />
              <div className="p-4">
                <h3 className="text-lg font-medium">Web Project 6</h3>
                <p className="text-gray-800 py-1">
                  A description of the sixth web project.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section>
        <ContactMe/>
        </section>
      </main>
    </div>
  );
};

export default Home;